// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderName           string   `protobuf:"bytes,2,opt,name=senderName,proto3" json:"senderName,omitempty"`
	Profile              string   `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *Message) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MessageRequest struct {
	TopicId              string   `protobuf:"bytes,1,opt,name=topicId,proto3" json:"topicId,omitempty"`
	StartFrom            uint32   `protobuf:"varint,2,opt,name=startFrom,proto3" json:"startFrom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetTopicId() string {
	if m != nil {
		return m.TopicId
	}
	return ""
}

func (m *MessageRequest) GetStartFrom() uint32 {
	if m != nil {
		return m.StartFrom
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*MessageRequest)(nil), "MessageRequest")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x3f, 0x6b, 0x85, 0x30,
	0x14, 0x47, 0xd1, 0x8a, 0xd6, 0x0b, 0x5a, 0xc8, 0x14, 0x4a, 0x29, 0xc5, 0xc9, 0x49, 0x4a, 0xbb,
	0x75, 0xec, 0x50, 0xda, 0xa1, 0x1d, 0x74, 0xeb, 0xa6, 0xf1, 0x56, 0x02, 0xcd, 0x4b, 0xde, 0x4d,
	0x7c, 0x9f, 0xff, 0x61, 0x34, 0xef, 0xcf, 0xf8, 0x3b, 0x27, 0xe4, 0xc0, 0x85, 0x42, 0xa1, 0xb5,
	0xfd, 0x84, 0x8d, 0x21, 0xed, 0x74, 0xa5, 0x20, 0xfb, 0x5e, 0x01, 0x2b, 0x21, 0x96, 0x23, 0x8f,
	0x9e, 0xa2, 0x3a, 0x6f, 0x63, 0x39, 0xb2, 0x47, 0x00, 0x8b, 0xbb, 0x11, 0xe9, 0xa7, 0x57, 0xc8,
	0x63, 0xcf, 0x2f, 0x08, 0xe3, 0x90, 0x19, 0xd2, 0x7f, 0xf2, 0x1f, 0xf9, 0x8d, 0x97, 0x61, 0x2e,
	0x66, 0xab, 0xf0, 0x64, 0x35, 0xdb, 0xac, 0x3e, 0xa1, 0xdc, 0x72, 0x2d, 0xee, 0x67, 0xb4, 0x6e,
	0x79, 0xeb, 0xb4, 0x91, 0xe2, 0x2b, 0xa4, 0xc3, 0x64, 0x0f, 0x90, 0x5b, 0xd7, 0x93, 0xfb, 0x20,
	0xad, 0x7c, 0xbe, 0x68, 0xcf, 0xe0, 0xe5, 0xed, 0xf4, 0x53, 0x87, 0x74, 0x90, 0x02, 0x59, 0x0d,
	0x79, 0x37, 0x0f, 0x56, 0x90, 0x1c, 0x90, 0xdd, 0x35, 0xd7, 0x9d, 0xfb, 0xdb, 0x00, 0x9e, 0xa3,
	0xf7, 0xf4, 0x37, 0x99, 0xc8, 0x88, 0x21, 0xf5, 0x37, 0x78, 0x3d, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x47, 0xd7, 0xee, 0xe5, 0x14, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageServiceClient interface {
	Subscribe(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (MessageService_SubscribeClient, error)
}

type messageServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessageServiceClient(cc *grpc.ClientConn) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) Subscribe(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (MessageService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MessageService_serviceDesc.Streams[0], "/MessageService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MessageService_SubscribeClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type messageServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *messageServiceSubscribeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageServiceServer is the server API for MessageService service.
type MessageServiceServer interface {
	Subscribe(*MessageRequest, MessageService_SubscribeServer) error
}

// UnimplementedMessageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (*UnimplementedMessageServiceServer) Subscribe(req *MessageRequest, srv MessageService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}

func RegisterMessageServiceServer(s *grpc.Server, srv MessageServiceServer) {
	s.RegisterService(&_MessageService_serviceDesc, srv)
}

func _MessageService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageServiceServer).Subscribe(m, &messageServiceSubscribeServer{stream})
}

type MessageService_SubscribeServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type messageServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *messageServiceSubscribeServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

var _MessageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _MessageService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "message.proto",
}
