// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topic.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TopicInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	NumReplies           uint32   `protobuf:"varint,3,opt,name=numReplies,proto3" json:"numReplies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicInfo) Reset()         { *m = TopicInfo{} }
func (m *TopicInfo) String() string { return proto.CompactTextString(m) }
func (*TopicInfo) ProtoMessage()    {}
func (*TopicInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{0}
}

func (m *TopicInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicInfo.Unmarshal(m, b)
}
func (m *TopicInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicInfo.Marshal(b, m, deterministic)
}
func (m *TopicInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicInfo.Merge(m, src)
}
func (m *TopicInfo) XXX_Size() int {
	return xxx_messageInfo_TopicInfo.Size(m)
}
func (m *TopicInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TopicInfo proto.InternalMessageInfo

func (m *TopicInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TopicInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TopicInfo) GetNumReplies() uint32 {
	if m != nil {
		return m.NumReplies
	}
	return 0
}

type TopicRequest struct {
	BoardId              string   `protobuf:"bytes,1,opt,name=boardId,proto3" json:"boardId,omitempty"`
	StartFrom            uint32   `protobuf:"varint,2,opt,name=startFrom,proto3" json:"startFrom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicRequest) Reset()         { *m = TopicRequest{} }
func (m *TopicRequest) String() string { return proto.CompactTextString(m) }
func (*TopicRequest) ProtoMessage()    {}
func (*TopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{1}
}

func (m *TopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicRequest.Unmarshal(m, b)
}
func (m *TopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicRequest.Marshal(b, m, deterministic)
}
func (m *TopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicRequest.Merge(m, src)
}
func (m *TopicRequest) XXX_Size() int {
	return xxx_messageInfo_TopicRequest.Size(m)
}
func (m *TopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopicRequest proto.InternalMessageInfo

func (m *TopicRequest) GetBoardId() string {
	if m != nil {
		return m.BoardId
	}
	return ""
}

func (m *TopicRequest) GetStartFrom() uint32 {
	if m != nil {
		return m.StartFrom
	}
	return 0
}

func init() {
	proto.RegisterType((*TopicInfo)(nil), "TopicInfo")
	proto.RegisterType((*TopicRequest)(nil), "TopicRequest")
}

func init() { proto.RegisterFile("topic.proto", fileDescriptor_7312ad0e4fa171e8) }

var fileDescriptor_7312ad0e4fa171e8 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc9, 0x2f, 0xc8,
	0x4c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x0a, 0xe4, 0xe2, 0x0c, 0x01, 0x71, 0x3d, 0xf3,
	0xd2, 0xf2, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98,
	0x32, 0x53, 0x84, 0x44, 0xb8, 0x58, 0x4b, 0x32, 0x4b, 0x72, 0x52, 0x25, 0x98, 0xc0, 0x42, 0x10,
	0x8e, 0x90, 0x1c, 0x17, 0x57, 0x5e, 0x69, 0x6e, 0x50, 0x6a, 0x41, 0x4e, 0x66, 0x6a, 0xb1, 0x04,
	0xb3, 0x02, 0xa3, 0x06, 0x6f, 0x10, 0x92, 0x88, 0x92, 0x1b, 0x17, 0x0f, 0xd8, 0xc8, 0xa0, 0xd4,
	0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x09, 0x2e, 0xf6, 0xa4, 0xfc, 0xc4, 0xa2, 0x14, 0x4f, 0x98,
	0xd1, 0x30, 0xae, 0x90, 0x0c, 0x17, 0x67, 0x71, 0x49, 0x62, 0x51, 0x89, 0x5b, 0x51, 0x7e, 0x2e,
	0xd8, 0x0e, 0xde, 0x20, 0x84, 0x80, 0x91, 0x09, 0xd4, 0x9c, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4,
	0x54, 0x21, 0x15, 0x2e, 0x56, 0x30, 0x5f, 0x88, 0x57, 0x0f, 0xd9, 0x7c, 0x29, 0x2e, 0x3d, 0xb8,
	0x0f, 0x0c, 0x18, 0x9d, 0xd8, 0xa2, 0x58, 0xd2, 0x8b, 0x0a, 0x92, 0x93, 0xd8, 0xc0, 0xfe, 0x33,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x02, 0x33, 0xf0, 0xee, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TopicServiceClient is the client API for TopicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TopicServiceClient interface {
	Topic(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (TopicService_TopicClient, error)
}

type topicServiceClient struct {
	cc *grpc.ClientConn
}

func NewTopicServiceClient(cc *grpc.ClientConn) TopicServiceClient {
	return &topicServiceClient{cc}
}

func (c *topicServiceClient) Topic(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (TopicService_TopicClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TopicService_serviceDesc.Streams[0], "/TopicService/Topic", opts...)
	if err != nil {
		return nil, err
	}
	x := &topicServiceTopicClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TopicService_TopicClient interface {
	Recv() (*TopicInfo, error)
	grpc.ClientStream
}

type topicServiceTopicClient struct {
	grpc.ClientStream
}

func (x *topicServiceTopicClient) Recv() (*TopicInfo, error) {
	m := new(TopicInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TopicServiceServer is the server API for TopicService service.
type TopicServiceServer interface {
	Topic(*TopicRequest, TopicService_TopicServer) error
}

// UnimplementedTopicServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTopicServiceServer struct {
}

func (*UnimplementedTopicServiceServer) Topic(req *TopicRequest, srv TopicService_TopicServer) error {
	return status.Errorf(codes.Unimplemented, "method Topic not implemented")
}

func RegisterTopicServiceServer(s *grpc.Server, srv TopicServiceServer) {
	s.RegisterService(&_TopicService_serviceDesc, srv)
}

func _TopicService_Topic_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TopicRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TopicServiceServer).Topic(m, &topicServiceTopicServer{stream})
}

type TopicService_TopicServer interface {
	Send(*TopicInfo) error
	grpc.ServerStream
}

type topicServiceTopicServer struct {
	grpc.ServerStream
}

func (x *topicServiceTopicServer) Send(m *TopicInfo) error {
	return x.ServerStream.SendMsg(m)
}

var _TopicService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TopicService",
	HandlerType: (*TopicServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Topic",
			Handler:       _TopicService_Topic_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "topic.proto",
}
