// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topics/messages.proto

package topics

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TopicInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	NumReplies           uint32   `protobuf:"varint,3,opt,name=numReplies,proto3" json:"numReplies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicInfo) Reset()         { *m = TopicInfo{} }
func (m *TopicInfo) String() string { return proto.CompactTextString(m) }
func (*TopicInfo) ProtoMessage()    {}
func (*TopicInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ca580cd16ef401c, []int{0}
}

func (m *TopicInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicInfo.Unmarshal(m, b)
}
func (m *TopicInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicInfo.Marshal(b, m, deterministic)
}
func (m *TopicInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicInfo.Merge(m, src)
}
func (m *TopicInfo) XXX_Size() int {
	return xxx_messageInfo_TopicInfo.Size(m)
}
func (m *TopicInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TopicInfo proto.InternalMessageInfo

func (m *TopicInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TopicInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TopicInfo) GetNumReplies() uint32 {
	if m != nil {
		return m.NumReplies
	}
	return 0
}

type TopicRequest struct {
	BoardId              string   `protobuf:"bytes,1,opt,name=boardId,proto3" json:"boardId,omitempty"`
	StartFrom            uint32   `protobuf:"varint,2,opt,name=startFrom,proto3" json:"startFrom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicRequest) Reset()         { *m = TopicRequest{} }
func (m *TopicRequest) String() string { return proto.CompactTextString(m) }
func (*TopicRequest) ProtoMessage()    {}
func (*TopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ca580cd16ef401c, []int{1}
}

func (m *TopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicRequest.Unmarshal(m, b)
}
func (m *TopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicRequest.Marshal(b, m, deterministic)
}
func (m *TopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicRequest.Merge(m, src)
}
func (m *TopicRequest) XXX_Size() int {
	return xxx_messageInfo_TopicRequest.Size(m)
}
func (m *TopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopicRequest proto.InternalMessageInfo

func (m *TopicRequest) GetBoardId() string {
	if m != nil {
		return m.BoardId
	}
	return ""
}

func (m *TopicRequest) GetStartFrom() uint32 {
	if m != nil {
		return m.StartFrom
	}
	return 0
}

func init() {
	proto.RegisterType((*TopicInfo)(nil), "topics.TopicInfo")
	proto.RegisterType((*TopicRequest)(nil), "topics.TopicRequest")
}

func init() { proto.RegisterFile("topics/messages.proto", fileDescriptor_3ca580cd16ef401c) }

var fileDescriptor_3ca580cd16ef401c = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xce, 0xc1, 0x0a, 0x82, 0x40,
	0x10, 0x06, 0x60, 0x34, 0x32, 0x1c, 0xb2, 0xc3, 0x52, 0xb0, 0x87, 0x08, 0xf1, 0xe4, 0xa9, 0x0e,
	0xbd, 0x83, 0xe0, 0xb1, 0xa5, 0x17, 0xd0, 0x9c, 0x62, 0x41, 0x9d, 0x6d, 0x67, 0x7c, 0xff, 0x68,
	0x45, 0xea, 0x36, 0xff, 0x77, 0xf8, 0xe7, 0x87, 0x83, 0x90, 0xb3, 0x0f, 0xbe, 0x0c, 0xc8, 0xdc,
	0xbc, 0x90, 0xcf, 0xce, 0x93, 0x90, 0x4a, 0x66, 0x2e, 0x6e, 0x90, 0xde, 0xbf, 0x57, 0x3d, 0x3e,
	0x49, 0xed, 0x20, 0xb6, 0x9d, 0x8e, 0xf2, 0xa8, 0x4c, 0x4d, 0x6c, 0x3b, 0xb5, 0x87, 0xb5, 0x58,
	0xe9, 0x51, 0xc7, 0x81, 0xe6, 0xa0, 0x4e, 0x00, 0xe3, 0x34, 0x18, 0x74, 0xbd, 0x45, 0xd6, 0xab,
	0x3c, 0x2a, 0x33, 0xf3, 0x27, 0x45, 0x05, 0xdb, 0x50, 0x69, 0xf0, 0x3d, 0x21, 0x8b, 0xd2, 0xb0,
	0x69, 0xa9, 0xf1, 0x5d, 0xbd, 0x54, 0x2f, 0x51, 0x1d, 0x21, 0x65, 0x69, 0xbc, 0x54, 0x9e, 0x86,
	0xf0, 0x23, 0x33, 0x3f, 0x68, 0x93, 0xb0, 0xf4, 0xfa, 0x09, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xbf,
	0x42, 0x14, 0xc2, 0x00, 0x00, 0x00,
}
