// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topics/services.proto

package topics

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("topics/services.proto", fileDescriptor_e9f43cec3218eacd) }

var fileDescriptor_e9f43cec3218eacd = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0xc9, 0x2f, 0xc8,
	0x4c, 0x2e, 0xd6, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x83, 0x08, 0x4b, 0xc1, 0xa4, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x61, 0xd2,
	0x46, 0x4e, 0x5c, 0x3c, 0x21, 0x20, 0x89, 0x60, 0x88, 0x2e, 0x21, 0x23, 0x2e, 0x56, 0x30, 0x5f,
	0x48, 0x44, 0x0f, 0xa2, 0x41, 0x0f, 0xcc, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x91, 0x12,
	0x44, 0x11, 0xf5, 0xcc, 0x4b, 0xcb, 0x37, 0x60, 0x4c, 0x62, 0x03, 0x1b, 0x65, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x92, 0x31, 0x01, 0x71, 0x82, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TopicServiceClient is the client API for TopicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TopicServiceClient interface {
	Topic(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (TopicService_TopicClient, error)
}

type topicServiceClient struct {
	cc *grpc.ClientConn
}

func NewTopicServiceClient(cc *grpc.ClientConn) TopicServiceClient {
	return &topicServiceClient{cc}
}

func (c *topicServiceClient) Topic(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (TopicService_TopicClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TopicService_serviceDesc.Streams[0], "/topics.TopicService/Topic", opts...)
	if err != nil {
		return nil, err
	}
	x := &topicServiceTopicClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TopicService_TopicClient interface {
	Recv() (*TopicInfo, error)
	grpc.ClientStream
}

type topicServiceTopicClient struct {
	grpc.ClientStream
}

func (x *topicServiceTopicClient) Recv() (*TopicInfo, error) {
	m := new(TopicInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TopicServiceServer is the server API for TopicService service.
type TopicServiceServer interface {
	Topic(*TopicRequest, TopicService_TopicServer) error
}

// UnimplementedTopicServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTopicServiceServer struct {
}

func (*UnimplementedTopicServiceServer) Topic(req *TopicRequest, srv TopicService_TopicServer) error {
	return status.Errorf(codes.Unimplemented, "method Topic not implemented")
}

func RegisterTopicServiceServer(s *grpc.Server, srv TopicServiceServer) {
	s.RegisterService(&_TopicService_serviceDesc, srv)
}

func _TopicService_Topic_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TopicRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TopicServiceServer).Topic(m, &topicServiceTopicServer{stream})
}

type TopicService_TopicServer interface {
	Send(*TopicInfo) error
	grpc.ServerStream
}

type topicServiceTopicServer struct {
	grpc.ServerStream
}

func (x *topicServiceTopicServer) Send(m *TopicInfo) error {
	return x.ServerStream.SendMsg(m)
}

var _TopicService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "topics.TopicService",
	HandlerType: (*TopicServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Topic",
			Handler:       _TopicService_Topic_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "topics/services.proto",
}
