# CAUTION!! DON'T USE THIS ENV FOR PRODUCTION!!
version: "3"
services:
  broker:
    image: nats
  db:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: real
      MONGO_INITDB_ROOT_PASSWORD: real
    volumes:
      - ./data/db:/data
      - ./config:/etc/mongo
  testdb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: real
      MONGO_INITDB_ROOT_PASSWORD: real
    tmpfs:
      - /data/db
    volumes:
      - ./config:/etc/mongo
  express:
    image: mongo-express:latest
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: real
      ME_CONFIG_MONGODB_ADMINPASSWORD: real
    ports:
      - 8081:8081
    depends_on:
      - db
  message:
    build:
      context: ./backend
      dockerfile: devel.dockerfile
      args:
        PKGNAME: message
    stop_signal: SIGINT
    restart: unless-stopped
    ports:
      - 50500:50505
    volumes:
      - ./backend:/opt/code
      - ./config:/etc/real
    depends_on:
      - db
      - testdb
    environment:
      CONFIG_NAME: devel
