// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderName           string               `protobuf:"bytes,2,opt,name=senderName,proto3" json:"senderName,omitempty"`
	PostTime             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=postTime,proto3" json:"postTime,omitempty"`
	Message              string               `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *Message) GetPostTime() *timestamp.Timestamp {
	if m != nil {
		return m.PostTime
	}
	return nil
}

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MessageRequest struct {
	TopicId              string   `protobuf:"bytes,1,opt,name=topicId,proto3" json:"topicId,omitempty"`
	StartFrom            uint32   `protobuf:"varint,2,opt,name=startFrom,proto3" json:"startFrom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetTopicId() string {
	if m != nil {
		return m.TopicId
	}
	return ""
}

func (m *MessageRequest) GetStartFrom() uint32 {
	if m != nil {
		return m.StartFrom
	}
	return 0
}

type PostRequest struct {
	TopicId              string   `protobuf:"bytes,1,opt,name=topicId,proto3" json:"topicId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NoDump               bool     `protobuf:"varint,3,opt,name=noDump,proto3" json:"noDump,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Recaptcha            string   `protobuf:"bytes,5,opt,name=recaptcha,proto3" json:"recaptcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostRequest) Reset()         { *m = PostRequest{} }
func (m *PostRequest) String() string { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()    {}
func (*PostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *PostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRequest.Unmarshal(m, b)
}
func (m *PostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRequest.Marshal(b, m, deterministic)
}
func (m *PostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRequest.Merge(m, src)
}
func (m *PostRequest) XXX_Size() int {
	return xxx_messageInfo_PostRequest.Size(m)
}
func (m *PostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostRequest proto.InternalMessageInfo

func (m *PostRequest) GetTopicId() string {
	if m != nil {
		return m.TopicId
	}
	return ""
}

func (m *PostRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PostRequest) GetNoDump() bool {
	if m != nil {
		return m.NoDump
	}
	return false
}

func (m *PostRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PostRequest) GetRecaptcha() string {
	if m != nil {
		return m.Recaptcha
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*MessageRequest)(nil), "MessageRequest")
	proto.RegisterType((*PostRequest)(nil), "PostRequest")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcb, 0x4e, 0xeb, 0x30,
	0x10, 0x86, 0x95, 0xde, 0x3b, 0xbd, 0x1c, 0xc9, 0x8b, 0xa3, 0x28, 0xe2, 0x52, 0x75, 0xd5, 0x95,
	0x8b, 0x8a, 0xc4, 0x03, 0x20, 0x84, 0x60, 0x01, 0x42, 0x69, 0x37, 0xb0, 0x73, 0xdc, 0xa1, 0x58,
	0xc2, 0xb5, 0xb1, 0x27, 0xbc, 0x04, 0x2f, 0x8d, 0xe2, 0xc6, 0xbd, 0xac, 0xd8, 0xe5, 0xff, 0x35,
	0x9a, 0xf9, 0xbe, 0x18, 0x46, 0x1a, 0xbd, 0x17, 0x1b, 0xe4, 0xd6, 0x19, 0x32, 0xd9, 0xe5, 0xc6,
	0x98, 0xcd, 0x27, 0xce, 0x43, 0x2a, 0xca, 0xf7, 0x39, 0x29, 0x8d, 0x9e, 0x84, 0xb6, 0xf5, 0xc0,
	0xd0, 0x93, 0xa0, 0xd2, 0xef, 0xd2, 0xf4, 0x27, 0x81, 0xee, 0xd3, 0x6e, 0x01, 0x1b, 0x43, 0x43,
	0xad, 0xd3, 0x64, 0x92, 0xcc, 0xfa, 0x79, 0x43, 0xad, 0xd9, 0x05, 0x80, 0xc7, 0xed, 0x1a, 0xdd,
	0xb3, 0xd0, 0x98, 0x36, 0x42, 0x7f, 0xd4, 0xb0, 0x1b, 0xe8, 0x59, 0xe3, 0x69, 0xa5, 0x34, 0xa6,
	0xcd, 0x49, 0x32, 0x1b, 0x2c, 0x32, 0xbe, 0xbb, 0xce, 0xe3, 0x75, 0xbe, 0x8a, 0xd7, 0xf3, 0xfd,
	0x2c, 0x4b, 0xa1, 0x5b, 0x33, 0xa7, 0xed, 0xb0, 0x34, 0xc6, 0xe9, 0x03, 0x8c, 0x6b, 0x98, 0x1c,
	0xbf, 0x4a, 0xf4, 0x54, 0xcd, 0x92, 0xb1, 0x4a, 0x3e, 0x46, 0xb0, 0x18, 0xd9, 0x19, 0xf4, 0x3d,
	0x09, 0x47, 0xf7, 0xce, 0xe8, 0x00, 0x37, 0xca, 0x0f, 0x45, 0xe5, 0x35, 0x78, 0x31, 0x9e, 0xfe,
	0xde, 0xc3, 0xa0, 0xb5, 0x3d, 0xf8, 0x85, 0x6f, 0xf6, 0x1f, 0x3a, 0x5b, 0x73, 0x57, 0x6a, 0x1b,
	0xbc, 0x7a, 0x79, 0x9d, 0x8e, 0xc9, 0x5b, 0x27, 0xe4, 0x15, 0x8d, 0x43, 0x29, 0x2c, 0xc9, 0x0f,
	0x51, 0x5b, 0x1d, 0x8a, 0xc5, 0xeb, 0xde, 0x6b, 0x89, 0xee, 0x5b, 0x49, 0x64, 0x33, 0xe8, 0x2f,
	0xcb, 0xc2, 0x4b, 0xa7, 0x0a, 0x64, 0xff, 0xf8, 0xa9, 0x75, 0xd6, 0x8b, 0xc5, 0x55, 0xc2, 0xce,
	0xa1, 0x55, 0x89, 0xb0, 0x21, 0x3f, 0xf2, 0xc9, 0xba, 0x7c, 0x19, 0x9e, 0xf1, 0xb6, 0xfd, 0xd6,
	0x74, 0x56, 0x16, 0x9d, 0xf0, 0xc7, 0xaf, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x33, 0xd6, 0x8d,
	0x80, 0x0e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageServiceClient interface {
	Subscribe(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (MessageService_SubscribeClient, error)
	Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*Status, error)
}

type messageServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessageServiceClient(cc *grpc.ClientConn) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) Subscribe(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (MessageService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MessageService_serviceDesc.Streams[0], "/MessageService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MessageService_SubscribeClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type messageServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *messageServiceSubscribeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageServiceClient) Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/MessageService/Post", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
type MessageServiceServer interface {
	Subscribe(*MessageRequest, MessageService_SubscribeServer) error
	Post(context.Context, *PostRequest) (*Status, error)
}

// UnimplementedMessageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (*UnimplementedMessageServiceServer) Subscribe(req *MessageRequest, srv MessageService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedMessageServiceServer) Post(ctx context.Context, req *PostRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Post not implemented")
}

func RegisterMessageServiceServer(s *grpc.Server, srv MessageServiceServer) {
	s.RegisterService(&_MessageService_serviceDesc, srv)
}

func _MessageService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageServiceServer).Subscribe(m, &messageServiceSubscribeServer{stream})
}

type MessageService_SubscribeServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type messageServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *messageServiceSubscribeServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _MessageService_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessageService/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Post(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Post",
			Handler:    _MessageService_Post_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _MessageService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "message.proto",
}
